name = "totally"
version = "1.2.0"

description = "TOTP (Time-based One-Time Password) for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "okkdev", repo = "totally" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
